=== Tasos500/Perfect-Ruler/Assets/Perfect Ruler Schema.json
{
	"$schema":"https://json-schema.org/draft/2020-12/schema",
	"type":"object",
	"properties":{
		"mod_creator":{
			"type":"string"
		},
		"mod_name":{
			"type":"string"
		},
		"description":{
			"type":"string"
		},
		"version":{
			"type":"string"
		},
		"cards":{
			"type":"array",
			"minItems":1,
			"items":{
				"type":"object",
				"properties":{
					"number":{
						"type":"string",
						"pattern":"^([0-9]{3})$"
					},
					"name":{
						"type":"string"
					},
					"dc":{
						"type":"integer",
						"minimum":0,
						"maximum":99
					},
					"attribute":{
						"enum":[
							"LIGHT",
							"DARK",
							"FIRE",
							"EARTH",
							"WATER",
							"WIND"
						]
					},
					"card_type":{
						"enum":[
							"DRAGON",
							"SPELLCASTER",
							"ZOMBIE",
							"WARRIOR",
							"BEAST_WARRIOR",
							"BEAST",
							"WINGED_BEAST",
							"FIEND",
							"FAIRY",
							"INSECT",
							"DINOSAUR",
							"REPTILE",
							"FISH",
							"SEA_SERPENT",
							"MACHINE",
							"THUNDER",
							"AQUA",
							"PYRO",
							"ROCK",
							"PLANT",
							"IMMORTAL",
							"MAGIC",
							"POWER_UP",
							"TRAP_LIMITED",
							"TRAP_FULL",
							"RITUAL"
						]
					},
					"level":{
						"type":"integer",
						"minimum":1,
						"maximum":12
					},
					"atk":{
						"type":"integer",
						"minimum":0,
						"maximum":9999
					},
					"def":{
						"type":"integer",
						"minimum":0,
						"maximum":9999
					},
					"effect":{
						"type":"object",
						"properties":{
							"effect_properties":{
								"type":"object",
								"properties":{
									"effect_type":{
										"enum":[
											"spellbind",
											"destroy_opponent",
											"heal_controller_to"
										]
									},
									"attribute1":{
										"type":[
											"string",
											"integer"
										]
									}
								},
								"required":[
									"effect_type"
								]
							}
						}
					},
					"fusions":{
						"type":"array",
						"minItems":1,
						"items":{
							"type":"object",
							"properties":{
								"product":{
									"type":"string",
									"pattern":"^([0-9]{3})$"
								},
								"material":{
									"type":"integer",
									"minimum":1,
									"maximum":2
								}
							}
						}
					},
					"externals":{
						"type":"array",
						"minItems":1,
						"items":{
							"type":"integer",
							"minimum":0
						}
					}
				},
				"required":[
					"number",
					"name",
					"dc",
					"card_type"
				],
				"if":{
					"anyOf":[
						{
							"properties":{
								"card_type":{
									"const":"MAGIC"
								}
							}
						},
						{
							"properties":{
								"card_type":{
									"const":"TRAP_FULL"
								}
							}
						},
						{
							"properties":{
								"card_type":{
									"const":"TRAP_LIMITED"
								}
							}
						},
						{
							"properties":{
								"card_type":{
									"const":"RITUAL"
								}
							}
						}
					]
				},
				"then":{
					"required":[
						"effect"
					]
				},
				"else":{
					"required":[
						"attribute",
						"level",
						"atk",
						"def"
					]
				}
			}
		},
		"fusions":{
			"type":"array",
			"items":{
				"type":"object",
				"properties":{
					"product":{
						"type":"object",
						"properties":{
							"number":{
								"type":"string",
								"pattern":"^([0-9]{3})$"
							},
							"set":{
								"type":"string",
								"pattern":"^[a-zA-Z0-9]+\\.[a-zA-Z0-9]+$"
							}
						},
						"required":[
							"number"
						]
					},
					"material1":{
						"type":"array",
						"items":{
							"type":"object",
							"properties":{
								"number":{
									"type":"string",
									"pattern":"^([0-9]{3})$"
								},
								"set":{
									"type":"string",
									"pattern":"^[a-zA-Z0-9]+\\.[a-zA-Z0-9]+$"
								}
							},
							"required":[
								"number"
							]
						}
					},
					"material2":{
						"type":"array",
						"items":{
							"type":"object",
							"properties":{
								"number":{
									"type":"string",
									"pattern":"^([0-9]{3})$"
								},
								"set":{
									"type":"string",
									"pattern":"^[a-zA-Z0-9]+\\.[a-zA-Z0-9]+$"
								}
							},
							"required":[
								"number"
							]
						}
					}
				},
				"required":[
					"product",
					"material1",
					"material2"
				]
			}
		}
	},
	"required":[
		"mod_creator",
		"mod_name",
		"cards"
	]
}

=== Tasos500/Perfect-Ruler/Assets/Perfect Ruler Test JSON.json
{
	"mod_creator":"Tasos500",
	"mod_name":"TestMod",
	"description":"A test mod.",
	"version":"1.0",
	"cards":[
		{
			"number":"000",
			"name":"Blue-Eyes White Dragon",
			"dc":55,
			"attribute":"LIGHT",
			"card_type":"DRAGON",
			"level":8,
			"atk":3000,
			"def":2500,
			"toon":false
		},
		{
			"number":"001",
			"name":"Seiyaryu",
			"dc":53,
			"attribute":"LIGHT",
			"card_type":"DRAGON",
			"level":7,
			"atk":2500,
			"def":2300,
			"toon":false
		},
		{
			"number":"002",
			"name":"Blue-Eyes Ultimate Dragon",
			"dc":83,
			"attribute":"LIGHT",
			"card_type":"DRAGON",
			"level":12,
			"atk":4500,
			"def":3800,
			"toon":false
		},
		{
			"number":"003",
			"name":"Kaiser Dragon",
			"dc":43,
			"attribute":"LIGHT",
			"card_type":"DRAGON",
			"level":7,
			"atk":2300,
			"def":2000,
			"toon":false
		},
		{
			"number":"004",
			"name":"Blackland Fire Dragon",
			"dc":23,
			"attribute":"DARK",
			"card_type":"DRAGON",
			"level":4,
			"atk":1500,
			"def":800,
			"toon":false,
			"fusions":[
				{
					"product":"007",
					"material":2
				},
				{
					"product":"024",
					"material":2
				}
			]
		},
		{
			"number":"005",
			"name":"Koumori Dragon",
			"dc":27,
			"attribute":"DARK",
			"card_type":"DRAGON",
			"level":4,
			"atk":1500,
			"def":1200,
			"toon":false,
			"fusions":[
				{
					"product":"007",
					"material":2
				},
				{
					"product":"024",
					"material":2
				}
			]
		},
		{
			"number":"006",
			"name":"Curse of Dragon",
			"dc":40,
			"attribute":"DARK",
			"card_type":"DRAGON",
			"level":5,
			"atk":2000,
			"def":1500,
			"toon":false,
			"fusions":[
				{
					"product":"007",
					"material":2
				},
				{
					"product":"024",
					"material":2
				}
			]
		},
		{
			"number":"007",
			"name":"Red-Eyes Black Dragon",
			"dc":44,
			"attribute":"DARK",
			"card_type":"DRAGON",
			"level":7,
			"atk":2400,
			"def":2000,
			"toon":false,
			"fusions":[
				{
					"product":"009",
					"material":1
				}
			]
		},
		{
			"number":"008",
			"name":"Darkfire Dragon",
			"dc":28,
			"attribute":"DARK",
			"card_type":"DRAGON",
			"level":4,
			"atk":1500,
			"def":1250,
			"toon":false,
			"fusions":[
				{
					"product":"007",
					"material":2
				},
				{
					"product":"024",
					"material":2
				}
			]
		},
		{
			"number":"009",
			"name":"Black Skull Dragon",
			"dc":57,
			"attribute":"DARK",
			"card_type":"DRAGON",
			"level":9,
			"atk":3200,
			"def":2500,
			"toon":false
		},
		{
			"number":"010",
			"name":"Tri-Horned Dragon",
			"dc":52,
			"attribute":"DARK",
			"card_type":"DRAGON",
			"level":8,
			"atk":2850,
			"def":2350,
			"toon":false
		},
		{
			"number":"011",
			"name":"Serpent Night Dragon",
			"dc":53,
			"attribute":"DARK",
			"card_type":"DRAGON",
			"level":7,
			"atk":2350,
			"def":2400,
			"toon":false,
			"fusions":[
				{
					"product":"007",
					"material":2
				},
				{
					"product":"024",
					"material":2
				}
			]
		},
		{
			"number":"012",
			"name":"Mikazukinoyaiba",
			"dc":46,
			"attribute":"DARK",
			"card_type":"DRAGON",
			"level":7,
			"atk":2200,
			"def":2350,
			"toon":false,
			"fusions":[
				{
					"product":"007",
					"material":2
				},
				{
					"product":"024",
					"material":2
				}
			]
		},
		{
			"number":"013",
			"name":"Yamadron",
			"dc":44,
			"attribute":"FIRE",
			"card_type":"DRAGON",
			"level":5,
			"atk":1600,
			"def":1800,
			"toon":false,
			"fusions":[
				{
					"product":"024",
					"material":2
				}
			],
			"effects":[
				{
					"trigger":"flipped_face_up",
					"effect":["transform_terrain_range_x_distance"],
					"attribute_effect":[1, "NORMAL"]
				}
			]
		},
		{
			"number":"014",
			"name":"Meteor B. Dragon",
			"dc":55,
			"attribute":"FIRE",
			"card_type":"DRAGON",
			"level":8,
			"atk":3500,
			"def":2000,
			"toon":false,
			"fusions":[
				{
					"product":"024",
					"material":2
				}
			]
		},
		{
			"number":"015",
			"name":"Tyhone #2",
			"dc":36,
			"attribute":"FIRE",
			"card_type":"DRAGON",
			"level":6,
			"atk":1700,
			"def":1900,
			"toon":false,
			"fusions":[
				{
					"product":"006",
					"material":1
				},
				{
					"product":"007",
					"material":1
				},
				{
					"product":"020",
					"material":1
				},
				{
					"product":"024",
					"material":2
				},
				{
					"product":"030",
					"material":2
				},
				{
					"product":"476",
					"material":2
				},
				{
					"product":"479",
					"material":2
				},
				{
					"product":"529",
					"material":1
				},
				{
					"product":"632",
					"material":1
				}
			]
		},
		{
			"number":"024",
			"name":"Thousand Dragon",
			"dc":44,
			"attribute":"WIND",
			"card_type":"DRAGON",
			"level":7,
			"atk":2400,
			"def":2000,
			"toon":false
		},
		{
			"number":"036",
			"name":"Time Wizard",
			"dc":14,
			"attribute":"LIGHT",
			"card_type":"SPELLCASTER",
			"level":2,
			"atk":500,
			"def":400,
			"toon":false,
			"fusions":[
				{
					"product":"024",
					"material":1
				},
				{
					"product":"035",
					"material":2
				},
				{
					"product":"124",
					"material":2
				},
				{
					"product":"312",
					"material":2
				},
				{
					"product":"339",
					"material":2
				},
				{
					"product":"536",
					"material":2
				},
				{
					"product":"544",
					"material":2
				},
				{
					"product":"584",
					"material":1
				}
			]
		},
		{
			"number":"294",
			"name":"Summoned Skull",
			"dc":37,
			"attribute":"DARK",
			"card_type":"FIEND",
			"level":6,
			"atk":2500,
			"def":1200,
			"toon":false,
			"fusions":[
				{
					"product":"009",
					"material":2
				}
			]
		},
		{
			"number":"326",
			"name":"Candle of Fate",
			"dc":16,
			"attribute":"DARK",
			"card_type":"FIEND",
			"level":2,
			"atk":600,
			"def":600,
			"toon":false,
			"effects":[
				{
					"trigger":"standby_face_up_defense",
					"effect":["stat_change_x"],
					"target":["cards_enemy"],
					"attribute_effect":[-100]
				}
			]
		},
		{
			"number":"417",
			"name":"Man-Eater Bug",
			"dc":16,
			"attribute":"EARTH",
			"card_type":"INSECT",
			"level":2,
			"atk":450,
			"def":600,
			"toon":false,
			"effects":[
				{
					"trigger":"flipped_face_up_battle",
					"effect":["destroy"],
					"target":["opponent"]
				}
			]
		},
		{
			"number":"707",
			"name":"Dian Keto the Cure Master",
			"dc":60,
			"card_type":"MAGIC",
			"effects":[
				{
					"effect":["lp_enemy_set_up_to_x"],
					"attribute_effect":[4000]
				}
			]
		},
		{
			"number":"801",
			"name":"Spellbinding Circle",
			"dc":30,
			"card_type":"TRAP_LIMITED",
			"effects":[
				{
					"effect":["spellbind"],
					"target":["trap_activator"],
					"attribute_effect":[3]
				}
			]
		}
	],
	"fusions":[
		{
			"product":{
				"number":"009"
			},
			"material1":[
				{
					"number":"007"
				}
			],
			"material2":[
				{
					"number":"294"
				}
			]
		}
	]
}
